default_session = "default_session"
search_submodules = true
recursive_submodules = true
full_path = true
session_sort_order = "LastAttached"

[[search_dirs]]
path = "~/work"
depth = 2

[[search_dirs]]
path = "~/personal/"
depth = 2

[[search_dirs]]
path = "~/.dotfiles/"
depth = 1

[[search_dirs]]
path = "~/.local/src"
depth = 1
