default_session = "default_session"
search_submodules = true
recursive_submodules = true
full_path = true

[[search_dirs]]
path = "~/work"
depth = 2

[[search_dirs]]
path = "~/personal/"
depth = 1

[[search_dirs]]
path = "~/.dotfiles/"
depth = 1
